V_NATIVE_TOKEN_ABI = [
    {"constant": True, "inputs": [], "name": "name", "outputs": [{"name": "", "type": "string"}], "payable": False,
     "stateMutability": "view", "type": "function"},
    {"constant": False, "inputs": [{"name": "spender", "type": "address"}, {"name": "amount", "type": "uint256"}],
     "name": "approve", "outputs": [{"name": "", "type": "bool"}], "payable": False, "stateMutability": "nonpayable",
     "type": "function"},
    {"constant": False, "inputs": [], "name": "mint", "outputs": [], "payable": True, "stateMutability": "payable",
     "type": "function"},
    {"constant": True, "inputs": [], "name": "reserveFactorMantissa", "outputs": [{"name": "", "type": "uint256"}],
     "payable": False, "stateMutability": "view", "type": "function"},
    {"constant": False, "inputs": [{"name": "account", "type": "address"}], "name": "borrowBalanceCurrent",
     "outputs": [{"name": "", "type": "uint256"}], "payable": False, "stateMutability": "nonpayable",
     "type": "function"},
    {"constant": True, "inputs": [], "name": "totalSupply", "outputs": [{"name": "", "type": "uint256"}],
     "payable": False, "stateMutability": "view", "type": "function"},
    {"constant": True, "inputs": [], "name": "exchangeRateStored", "outputs": [{"name": "", "type": "uint256"}],
     "payable": False, "stateMutability": "view", "type": "function"}, {"constant": False,
                                                                        "inputs": [{"name": "src", "type": "address"},
                                                                                   {"name": "dst", "type": "address"},
                                                                                   {"name": "amount",
                                                                                    "type": "uint256"}],
                                                                        "name": "transferFrom",
                                                                        "outputs": [{"name": "", "type": "bool"}],
                                                                        "payable": False,
                                                                        "stateMutability": "nonpayable",
                                                                        "type": "function"},
    {"constant": True, "inputs": [], "name": "pendingAdmin", "outputs": [{"name": "", "type": "address"}],
     "payable": False, "stateMutability": "view", "type": "function"},
    {"constant": True, "inputs": [], "name": "decimals", "outputs": [{"name": "", "type": "uint256"}], "payable": False,
     "stateMutability": "view", "type": "function"},
    {"constant": False, "inputs": [{"name": "owner", "type": "address"}], "name": "balanceOfUnderlying",
     "outputs": [{"name": "", "type": "uint256"}], "payable": False, "stateMutability": "nonpayable",
     "type": "function"},
    {"constant": True, "inputs": [], "name": "getCash", "outputs": [{"name": "", "type": "uint256"}], "payable": False,
     "stateMutability": "view", "type": "function"},
    {"constant": False, "inputs": [{"name": "newComptroller", "type": "address"}], "name": "_setComptroller",
     "outputs": [{"name": "", "type": "uint256"}], "payable": False, "stateMutability": "nonpayable",
     "type": "function"},
    {"constant": True, "inputs": [], "name": "totalBorrows", "outputs": [{"name": "", "type": "uint256"}],
     "payable": False, "stateMutability": "view", "type": "function"},
    {"constant": False, "inputs": [], "name": "repayBorrow", "outputs": [], "payable": True,
     "stateMutability": "payable", "type": "function"},
    {"constant": True, "inputs": [], "name": "comptroller", "outputs": [{"name": "", "type": "address"}],
     "payable": False, "stateMutability": "view", "type": "function"},
    {"constant": False, "inputs": [{"name": "reduceAmount", "type": "uint256"}], "name": "_reduceReserves",
     "outputs": [{"name": "", "type": "uint256"}], "payable": False, "stateMutability": "nonpayable",
     "type": "function"}, {"constant": True, "inputs": [], "name": "initialExchangeRateMantissa",
                           "outputs": [{"name": "", "type": "uint256"}], "payable": False, "stateMutability": "view",
                           "type": "function"},
    {"constant": True, "inputs": [], "name": "accrualBlockNumber", "outputs": [{"name": "", "type": "uint256"}],
     "payable": False, "stateMutability": "view", "type": "function"},
    {"constant": True, "inputs": [{"name": "owner", "type": "address"}], "name": "balanceOf",
     "outputs": [{"name": "", "type": "uint256"}], "payable": False, "stateMutability": "view", "type": "function"},
    {"constant": False, "inputs": [], "name": "totalBorrowsCurrent", "outputs": [{"name": "", "type": "uint256"}],
     "payable": False, "stateMutability": "nonpayable", "type": "function"},
    {"constant": False, "inputs": [{"name": "redeemAmount", "type": "uint256"}], "name": "redeemUnderlying",
     "outputs": [{"name": "", "type": "uint256"}], "payable": False, "stateMutability": "nonpayable",
     "type": "function"},
    {"constant": True, "inputs": [], "name": "totalReserves", "outputs": [{"name": "", "type": "uint256"}],
     "payable": False, "stateMutability": "view", "type": "function"},
    {"constant": True, "inputs": [], "name": "symbol", "outputs": [{"name": "", "type": "string"}], "payable": False,
     "stateMutability": "view", "type": "function"},
    {"constant": True, "inputs": [{"name": "account", "type": "address"}], "name": "borrowBalanceStored",
     "outputs": [{"name": "", "type": "uint256"}], "payable": False, "stateMutability": "view", "type": "function"},
    {"constant": False, "inputs": [], "name": "accrueInterest", "outputs": [{"name": "", "type": "uint256"}],
     "payable": False, "stateMutability": "nonpayable", "type": "function"},
    {"constant": False, "inputs": [{"name": "dst", "type": "address"}, {"name": "amount", "type": "uint256"}],
     "name": "transfer", "outputs": [{"name": "", "type": "bool"}], "payable": False, "stateMutability": "nonpayable",
     "type": "function"},
    {"constant": True, "inputs": [], "name": "borrowIndex", "outputs": [{"name": "", "type": "uint256"}],
     "payable": False, "stateMutability": "view", "type": "function"}, {"constant": False, "inputs": [
        {"name": "borrower", "type": "address"}, {"name": "cTokenCollateral", "type": "address"}],
                                                                        "name": "liquidateBorrow", "outputs": [],
                                                                        "payable": True, "stateMutability": "payable",
                                                                        "type": "function"},
    {"constant": True, "inputs": [], "name": "supplyRatePerBlock", "outputs": [{"name": "", "type": "uint256"}],
     "payable": False, "stateMutability": "view", "type": "function"}, {"constant": False, "inputs": [
        {"name": "liquidator", "type": "address"}, {"name": "borrower", "type": "address"},
        {"name": "seizeTokens", "type": "uint256"}], "name": "seize", "outputs": [{"name": "", "type": "uint256"}],
                                                                        "payable": False,
                                                                        "stateMutability": "nonpayable",
                                                                        "type": "function"},
    {"constant": False, "inputs": [{"name": "newPendingAdmin", "type": "address"}], "name": "_setPendingAdmin",
     "outputs": [{"name": "", "type": "uint256"}], "payable": False, "stateMutability": "nonpayable",
     "type": "function"},
    {"constant": False, "inputs": [], "name": "exchangeRateCurrent", "outputs": [{"name": "", "type": "uint256"}],
     "payable": False, "stateMutability": "nonpayable", "type": "function"},
    {"constant": True, "inputs": [{"name": "account", "type": "address"}], "name": "getAccountSnapshot",
     "outputs": [{"name": "", "type": "uint256"}, {"name": "", "type": "uint256"}, {"name": "", "type": "uint256"},
                 {"name": "", "type": "uint256"}], "payable": False, "stateMutability": "view", "type": "function"},
    {"constant": False, "inputs": [{"name": "borrowAmount", "type": "uint256"}], "name": "borrow",
     "outputs": [{"name": "", "type": "uint256"}], "payable": False, "stateMutability": "nonpayable",
     "type": "function"}, {"constant": False, "inputs": [{"name": "redeemTokens", "type": "uint256"}], "name": "redeem",
                           "outputs": [{"name": "", "type": "uint256"}], "payable": False,
                           "stateMutability": "nonpayable", "type": "function"},
    {"constant": True, "inputs": [{"name": "owner", "type": "address"}, {"name": "spender", "type": "address"}],
     "name": "allowance", "outputs": [{"name": "", "type": "uint256"}], "payable": False, "stateMutability": "view",
     "type": "function"},
    {"constant": False, "inputs": [{"name": "borrower", "type": "address"}], "name": "repayBorrowBehalf", "outputs": [],
     "payable": True, "stateMutability": "payable", "type": "function"},
    {"constant": False, "inputs": [], "name": "_acceptAdmin", "outputs": [{"name": "", "type": "uint256"}],
     "payable": False, "stateMutability": "nonpayable", "type": "function"},
    {"constant": False, "inputs": [{"name": "newInterestRateModel", "type": "address"}],
     "name": "_setInterestRateModel", "outputs": [{"name": "", "type": "uint256"}], "payable": False,
     "stateMutability": "nonpayable", "type": "function"},
    {"constant": True, "inputs": [], "name": "interestRateModel", "outputs": [{"name": "", "type": "address"}],
     "payable": False, "stateMutability": "view", "type": "function"},
    {"constant": True, "inputs": [], "name": "admin", "outputs": [{"name": "", "type": "address"}], "payable": False,
     "stateMutability": "view", "type": "function"},
    {"constant": True, "inputs": [], "name": "borrowRatePerBlock", "outputs": [{"name": "", "type": "uint256"}],
     "payable": False, "stateMutability": "view", "type": "function"},
    {"constant": False, "inputs": [{"name": "newReserveFactorMantissa", "type": "uint256"}],
     "name": "_setReserveFactor", "outputs": [{"name": "", "type": "uint256"}], "payable": False,
     "stateMutability": "nonpayable", "type": "function"},
    {"constant": True, "inputs": [], "name": "isCToken", "outputs": [{"name": "", "type": "bool"}], "payable": False,
     "stateMutability": "view", "type": "function"}, {
        "inputs": [{"name": "comptroller_", "type": "address"}, {"name": "interestRateModel_", "type": "address"},
                   {"name": "initialExchangeRateMantissa_", "type": "uint256"}, {"name": "name_", "type": "string"},
                   {"name": "symbol_", "type": "string"}, {"name": "decimals_", "type": "uint256"}], "payable": False,
        "stateMutability": "nonpayable", "type": "constructor"},
    {"payable": True, "stateMutability": "payable", "type": "fallback"}, {"anonymous": False, "inputs": [
        {"indexed": False, "name": "interestAccumulated", "type": "uint256"},
        {"indexed": False, "name": "borrowIndex", "type": "uint256"},
        {"indexed": False, "name": "totalBorrows", "type": "uint256"}], "name": "AccrueInterest", "type": "event"},
    {"anonymous": False, "inputs": [{"indexed": False, "name": "minter", "type": "address"},
                                    {"indexed": False, "name": "mintAmount", "type": "uint256"},
                                    {"indexed": False, "name": "mintTokens", "type": "uint256"}], "name": "Mint",
     "type": "event"}, {"anonymous": False, "inputs": [{"indexed": False, "name": "redeemer", "type": "address"},
                                                       {"indexed": False, "name": "redeemAmount", "type": "uint256"},
                                                       {"indexed": False, "name": "redeemTokens", "type": "uint256"}],
                        "name": "Redeem", "type": "event"}, {"anonymous": False, "inputs": [
        {"indexed": False, "name": "borrower", "type": "address"},
        {"indexed": False, "name": "borrowAmount", "type": "uint256"},
        {"indexed": False, "name": "accountBorrows", "type": "uint256"},
        {"indexed": False, "name": "totalBorrows", "type": "uint256"}], "name": "Borrow", "type": "event"},
    {"anonymous": False, "inputs": [{"indexed": False, "name": "payer", "type": "address"},
                                    {"indexed": False, "name": "borrower", "type": "address"},
                                    {"indexed": False, "name": "repayAmount", "type": "uint256"},
                                    {"indexed": False, "name": "accountBorrows", "type": "uint256"},
                                    {"indexed": False, "name": "totalBorrows", "type": "uint256"}],
     "name": "RepayBorrow", "type": "event"}, {"anonymous": False,
                                               "inputs": [{"indexed": False, "name": "liquidator", "type": "address"},
                                                          {"indexed": False, "name": "borrower", "type": "address"},
                                                          {"indexed": False, "name": "repayAmount", "type": "uint256"},
                                                          {"indexed": False, "name": "cTokenCollateral",
                                                           "type": "address"},
                                                          {"indexed": False, "name": "seizeTokens", "type": "uint256"}],
                                               "name": "LiquidateBorrow", "type": "event"}, {"anonymous": False,
                                                                                             "inputs": [
                                                                                                 {"indexed": False,
                                                                                                  "name": "oldPendingAdmin",
                                                                                                  "type": "address"},
                                                                                                 {"indexed": False,
                                                                                                  "name": "newPendingAdmin",
                                                                                                  "type": "address"}],
                                                                                             "name": "NewPendingAdmin",
                                                                                             "type": "event"},
    {"anonymous": False, "inputs": [{"indexed": False, "name": "oldAdmin", "type": "address"},
                                    {"indexed": False, "name": "newAdmin", "type": "address"}], "name": "NewAdmin",
     "type": "event"}, {"anonymous": False, "inputs": [{"indexed": False, "name": "oldComptroller", "type": "address"},
                                                       {"indexed": False, "name": "newComptroller", "type": "address"}],
                        "name": "NewComptroller", "type": "event"}, {"anonymous": False, "inputs": [
        {"indexed": False, "name": "oldInterestRateModel", "type": "address"},
        {"indexed": False, "name": "newInterestRateModel", "type": "address"}], "name": "NewMarketInterestRateModel",
                                                                     "type": "event"}, {"anonymous": False, "inputs": [
        {"indexed": False, "name": "oldReserveFactorMantissa", "type": "uint256"},
        {"indexed": False, "name": "newReserveFactorMantissa", "type": "uint256"}], "name": "NewReserveFactor",
                                                                                        "type": "event"},
    {"anonymous": False, "inputs": [{"indexed": False, "name": "admin", "type": "address"},
                                    {"indexed": False, "name": "reduceAmount", "type": "uint256"},
                                    {"indexed": False, "name": "newTotalReserves", "type": "uint256"}],
     "name": "ReservesReduced", "type": "event"}, {"anonymous": False,
                                                   "inputs": [{"indexed": False, "name": "error", "type": "uint256"},
                                                              {"indexed": False, "name": "info", "type": "uint256"},
                                                              {"indexed": False, "name": "detail", "type": "uint256"}],
                                                   "name": "Failure", "type": "event"}, {"anonymous": False, "inputs": [
        {"indexed": True, "name": "from", "type": "address"}, {"indexed": True, "name": "to", "type": "address"},
        {"indexed": False, "name": "amount", "type": "uint256"}], "name": "Transfer", "type": "event"},
    {"anonymous": False, "inputs": [{"indexed": True, "name": "owner", "type": "address"},
                                    {"indexed": True, "name": "spender", "type": "address"},
                                    {"indexed": False, "name": "amount", "type": "uint256"}], "name": "Approval",
     "type": "event"}]
